SELECT
    BLOCKED.INST_ID,
    BLOCKED.SID AS blocked_session,
    BLOCKED.SECONDS_IN_WAIT / 60 AS wait_time_minutes,
    BLOCKER.SID AS blocking_session,
    BLOCKER.SQL_ID AS blocker_sql_id,
    BLOCKER.USERNAME AS blocker_username,
    BLOCKER.MACHINE AS blocker_machine
FROM
    GV$SESSION BLOCKED
JOIN
    GV$SESSION BLOCKER ON BLOCKED.BLOCKING_SESSION = BLOCKER.SID AND BLOCKED.BLOCKING_INSTANCE = BLOCKER.INST_ID
WHERE
    BLOCKED.BLOCKING_SESSION IS NOT NULL
ORDER BY
    wait_time_minutes DESC